packages: []
catalogs:
  build:
    '@mdit/plugin-figure': ^0.22.2
    '@shikijs/markdown-it': ^3.21.0
    '@shikijs/transformers': ^3.2.1
    '@shikijs/twoslash': ^3.21.0
    '@unocss/preset-web-fonts': ^66.0.0
    '@vitejs/plugin-vue': ^6.0.3
    gray-matter: ^4.0.3
    markdown-it: ^14.1.0
    markdown-it-anchor: ^9.2.0
    markdown-it-github-alerts: ^1.0.1
    markdown-it-link-attributes: ^4.0.1
    markdown-it-footnote: ^4.0.0
    markdown-it-table-of-contents: ^1.1.0
    unocss: ^66.6.0
    unplugin-auto-import: ^21.0.0
    unplugin-icons: ^23.0.1
    unplugin-vue-components: ^31.0.0
    unplugin-vue-markdown: ^29.2.0
    unplugin-vue-router: ^0.19.2
    vite: ^7.3.1
    vite-plugin-inspect: ^11.3.3
    vite-plugin-optimize-exclude: ^0.0.1
    vite-ssg: ^28.2.2
    vite-svg-loader: ^5.1.0

  dev:
    '@iconify/json': ^2.2.431
    '@octokit/core': ^6.1.4
    '@octokit/rest': ^22.0.1
    ansis: ^4.2.0
    cross-env: ^10.1.0
    degit: ^2.8.4
    diacritics: ^1.3.0
    fast-glob: ^3.3.3
    feed: ^5.2.0
    fs-extra: ^11.3.3
    pnpm: ^10.10.0
    prompts: ^2.4.2
    rimraf: ^6.1.2
    sharp: 0.34.5
    simple-git: ^3.30.0
    tsx: ^4.21.0
    typescript: ~5.9.3
    blurhash: ^2.0.5
    ofetch: ^1.5.1

  frontend:
    '@lhlyu/vue-virtual-waterfall': ^1.0.8
    '@unhead/vue': ^2.1.2
    '@unocss/reset': ^66.6.0
    '@vueuse/core': ^14.1.0
    '@unpic/placeholder': ^0.1.2
    dayjs: ^1.11.19
    tinylunar: ^1.0.0
    floating-vue: ^5.2.2
    livephotoskit: ^1.5.6
    nprogress: ^0.2.0
    shiki: ^3.21.0
    vue: ^3.5.27
    vue-router: ^4.6.4
    vue-router-better-scroller: ^0.0.0

  types:
    '@types/degit': ^2.8.6
    '@types/diacritics': ^1.3.3
    '@types/fs-extra': ^11.0.4
    '@types/markdown-it': ^14.1.2
    '@types/markdown-it-footnote': ^3.0.4
    '@types/markdown-it-link-attributes': ^3.0.5
    '@types/nprogress': ^0.2.3
    '@types/prompts': ^2.4.9
    '@types/node': ^25.0.3
onlyBuiltDependencies:
  - esbuild
  - sharp
