/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...404]': RouteRecordInfo<'/[...404]', '/:404(.*)', { 404: ParamValue<true> }, { 404: ParamValue<false> }>,
    '/bookmarks': RouteRecordInfo<'/bookmarks', '/bookmarks', Record<never, never>, Record<never, never>>,
    '/notes/': RouteRecordInfo<'/notes/', '/notes', Record<never, never>, Record<never, never>>,
    '/notes/hugo-build-static-blog': RouteRecordInfo<'/notes/hugo-build-static-blog', '/notes/hugo-build-static-blog', Record<never, never>, Record<never, never>>,
    '/notes/in-ubuntu-setting-node-environment': RouteRecordInfo<'/notes/in-ubuntu-setting-node-environment', '/notes/in-ubuntu-setting-node-environment', Record<never, never>, Record<never, never>>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/memories-and-impressions': RouteRecordInfo<'/posts/memories-and-impressions', '/posts/memories-and-impressions', Record<never, never>, Record<never, never>>,
    '/posts/miss-unseen': RouteRecordInfo<'/posts/miss-unseen', '/posts/miss-unseen', Record<never, never>, Record<never, never>>,
    '/strange-thinkings': RouteRecordInfo<'/strange-thinkings', '/strange-thinkings', Record<never, never>, Record<never, never>>,
  }
}
