name: Blog CI/CD

on:
  push:
    branches: 
      - main

env:
  TZ: Asia/Shanghai

jobs:
  blog-cicd:
    name: blog build & deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout codes
      uses: actions/checkout@v4

    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: '20.18.1'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Build
      run: pnpm run build

    - name: Deploy blog
      env: 
        GITHUB_REPO: github.com/ihzurgnauh/ihzurgnauh.github.io
      run: |
        cd ./dist && git config --global init.defaultBranch main && git init && git add .
        git config user.name '${{ vars.GH_NAME }}'
        git config user.email '${{ vars.GH_EMAIL }}'
        git add .
        git commit -m "Auto-build by GitHub Actions [$(date +'%Y-%m-%d %H:%M:%S')]"
        git push --force --quiet "https://${{ secrets.GH_TOKEN }}@$GITHUB_REPO" main
